/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// PurchaseAPIService PurchaseAPI service
type PurchaseAPIService service

type ApiPurchasesDeliverPostRequest struct {
	ctx context.Context
	ApiService *PurchaseAPIService
	type_ *int32
	agent *string
	digipayVersion *string
	deliverRequest *DeliverRequest
}

func (r ApiPurchasesDeliverPostRequest) Type_(type_ int32) ApiPurchasesDeliverPostRequest {
	r.type_ = &type_
	return r
}

func (r ApiPurchasesDeliverPostRequest) Agent(agent string) ApiPurchasesDeliverPostRequest {
	r.agent = &agent
	return r
}

func (r ApiPurchasesDeliverPostRequest) DigipayVersion(digipayVersion string) ApiPurchasesDeliverPostRequest {
	r.digipayVersion = &digipayVersion
	return r
}

func (r ApiPurchasesDeliverPostRequest) DeliverRequest(deliverRequest DeliverRequest) ApiPurchasesDeliverPostRequest {
	r.deliverRequest = &deliverRequest
	return r
}

func (r ApiPurchasesDeliverPostRequest) Execute() (*DeliverResponse, *http.Response, error) {
	return r.ApiService.PurchasesDeliverPostExecute(r)
}

/*
PurchasesDeliverPost Deliver Purchase

Marks the purchased goods/services as delivered. Mandatory step for CREDIT and BNPL type purchases only, must be called after Verify

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPurchasesDeliverPostRequest
*/
func (a *PurchaseAPIService) PurchasesDeliverPost(ctx context.Context) ApiPurchasesDeliverPostRequest {
	return ApiPurchasesDeliverPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return DeliverResponse
func (a *PurchaseAPIService) PurchasesDeliverPostExecute(r ApiPurchasesDeliverPostRequest) (*DeliverResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DeliverResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PurchaseAPIService.PurchasesDeliverPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/purchases/deliver"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.type_ == nil {
		return localVarReturnValue, nil, reportError("type_ is required and must be specified")
	}
	if r.agent == nil {
		return localVarReturnValue, nil, reportError("agent is required and must be specified")
	}
	if r.digipayVersion == nil {
		return localVarReturnValue, nil, reportError("digipayVersion is required and must be specified")
	}
	if r.deliverRequest == nil {
		return localVarReturnValue, nil, reportError("deliverRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "type", r.type_, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Agent", r.agent, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Digipay-Version", r.digipayVersion, "simple", "")
	// body params
	localVarPostBody = r.deliverRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPurchasesVerifyPostRequest struct {
	ctx context.Context
	ApiService *PurchaseAPIService
	type_ *int32
	agent *string
	digipayVersion *string
	verifyRequest *VerifyRequest
}

func (r ApiPurchasesVerifyPostRequest) Type_(type_ int32) ApiPurchasesVerifyPostRequest {
	r.type_ = &type_
	return r
}

func (r ApiPurchasesVerifyPostRequest) Agent(agent string) ApiPurchasesVerifyPostRequest {
	r.agent = &agent
	return r
}

func (r ApiPurchasesVerifyPostRequest) DigipayVersion(digipayVersion string) ApiPurchasesVerifyPostRequest {
	r.digipayVersion = &digipayVersion
	return r
}

func (r ApiPurchasesVerifyPostRequest) VerifyRequest(verifyRequest VerifyRequest) ApiPurchasesVerifyPostRequest {
	r.verifyRequest = &verifyRequest
	return r
}

func (r ApiPurchasesVerifyPostRequest) Execute() (*VerifyResponse, *http.Response, error) {
	return r.ApiService.PurchasesVerifyPostExecute(r)
}

/*
PurchasesVerifyPost Verify Purchase

Confirms the purchase referenced by the ticket's trackingCode after the customer returns from the payment page

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPurchasesVerifyPostRequest
*/
func (a *PurchaseAPIService) PurchasesVerifyPost(ctx context.Context) ApiPurchasesVerifyPostRequest {
	return ApiPurchasesVerifyPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return VerifyResponse
func (a *PurchaseAPIService) PurchasesVerifyPostExecute(r ApiPurchasesVerifyPostRequest) (*VerifyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *VerifyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PurchaseAPIService.PurchasesVerifyPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/purchases/verify"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.type_ == nil {
		return localVarReturnValue, nil, reportError("type_ is required and must be specified")
	}
	if r.agent == nil {
		return localVarReturnValue, nil, reportError("agent is required and must be specified")
	}
	if r.digipayVersion == nil {
		return localVarReturnValue, nil, reportError("digipayVersion is required and must be specified")
	}
	if r.verifyRequest == nil {
		return localVarReturnValue, nil, reportError("verifyRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "type", r.type_, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Agent", r.agent, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Digipay-Version", r.digipayVersion, "simple", "")
	// body params
	localVarPostBody = r.verifyRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiTicketsBusinessPostRequest struct {
	ctx context.Context
	ApiService *PurchaseAPIService
	type_ *int32
	agent *string
	digipayVersion *string
	ticketRequest *TicketRequest
}

func (r ApiTicketsBusinessPostRequest) Type_(type_ int32) ApiTicketsBusinessPostRequest {
	r.type_ = &type_
	return r
}

func (r ApiTicketsBusinessPostRequest) Agent(agent string) ApiTicketsBusinessPostRequest {
	r.agent = &agent
	return r
}

func (r ApiTicketsBusinessPostRequest) DigipayVersion(digipayVersion string) ApiTicketsBusinessPostRequest {
	r.digipayVersion = &digipayVersion
	return r
}

func (r ApiTicketsBusinessPostRequest) TicketRequest(ticketRequest TicketRequest) ApiTicketsBusinessPostRequest {
	r.ticketRequest = &ticketRequest
	return r
}

func (r ApiTicketsBusinessPostRequest) Execute() (*TicketResponse, *http.Response, error) {
	return r.ApiService.TicketsBusinessPostExecute(r)
}

/*
TicketsBusinessPost Create Purchase Ticket

Initiates a purchase (Wallet or BNPL depending on the type query param) and returns a redirectUrl for the customer to complete payment on

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiTicketsBusinessPostRequest
*/
func (a *PurchaseAPIService) TicketsBusinessPost(ctx context.Context) ApiTicketsBusinessPostRequest {
	return ApiTicketsBusinessPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return TicketResponse
func (a *PurchaseAPIService) TicketsBusinessPostExecute(r ApiTicketsBusinessPostRequest) (*TicketResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TicketResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PurchaseAPIService.TicketsBusinessPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/tickets/business"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.type_ == nil {
		return localVarReturnValue, nil, reportError("type_ is required and must be specified")
	}
	if r.agent == nil {
		return localVarReturnValue, nil, reportError("agent is required and must be specified")
	}
	if r.digipayVersion == nil {
		return localVarReturnValue, nil, reportError("digipayVersion is required and must be specified")
	}
	if r.ticketRequest == nil {
		return localVarReturnValue, nil, reportError("ticketRequest is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "type", r.type_, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Agent", r.agent, "simple", "")
	parameterAddToHeaderOrQuery(localVarHeaderParams, "Digipay-Version", r.digipayVersion, "simple", "")
	// body params
	localVarPostBody = r.ticketRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v ErrorResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
