/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"fmt"
)

// checks if the RefundResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundResponse{}

// RefundResponse struct for RefundResponse
type RefundResponse struct {
	Result Result `json:"result"`
	// tracking code of the refund itself, distinct from saleTrackingCode
	TrackingCode *string `json:"trackingCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RefundResponse RefundResponse

// NewRefundResponse instantiates a new RefundResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundResponse(result Result) *RefundResponse {
	this := RefundResponse{}
	this.Result = result
	return &this
}

// NewRefundResponseWithDefaults instantiates a new RefundResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundResponseWithDefaults() *RefundResponse {
	this := RefundResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *RefundResponse) GetResult() Result {
	if o == nil {
		var ret Result
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetResultOk() (*Result, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *RefundResponse) SetResult(v Result) {
	o.Result = v
}

// GetTrackingCode returns the TrackingCode field value if set, zero value otherwise.
func (o *RefundResponse) GetTrackingCode() string {
	if o == nil || IsNil(o.TrackingCode) {
		var ret string
		return ret
	}
	return *o.TrackingCode
}

// GetTrackingCodeOk returns a tuple with the TrackingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundResponse) GetTrackingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingCode) {
		return nil, false
	}
	return o.TrackingCode, true
}

// HasTrackingCode returns a boolean if a field has been set.
func (o *RefundResponse) HasTrackingCode() bool {
	if o != nil && !IsNil(o.TrackingCode) {
		return true
	}

	return false
}

// SetTrackingCode gets a reference to the given string and assigns it to the TrackingCode field.
func (o *RefundResponse) SetTrackingCode(v string) {
	o.TrackingCode = &v
}

func (o RefundResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	if !IsNil(o.TrackingCode) {
		toSerialize["trackingCode"] = o.TrackingCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RefundResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefundResponse := _RefundResponse{}

	err = json.Unmarshal(data, &varRefundResponse)

	if err != nil {
		return err
	}

	*o = RefundResponse(varRefundResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		delete(additionalProperties, "trackingCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRefundResponse struct {
	value *RefundResponse
	isSet bool
}

func (v NullableRefundResponse) Get() *RefundResponse {
	return v.value
}

func (v *NullableRefundResponse) Set(val *RefundResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundResponse(val *RefundResponse) *NullableRefundResponse {
	return &NullableRefundResponse{value: val, isSet: true}
}

func (v NullableRefundResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


