/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"fmt"
)

// checks if the TicketResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TicketResponse{}

// TicketResponse struct for TicketResponse
type TicketResponse struct {
	Result Result `json:"result"`
	// unique identifier for this purchase session
	Ticket string `json:"ticket"`
	// customer is redirected here to complete payment
	RedirectUrl string `json:"redirectUrl"`
	AdditionalProperties map[string]interface{}
}

type _TicketResponse TicketResponse

// NewTicketResponse instantiates a new TicketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTicketResponse(result Result, ticket string, redirectUrl string) *TicketResponse {
	this := TicketResponse{}
	this.Result = result
	this.Ticket = ticket
	this.RedirectUrl = redirectUrl
	return &this
}

// NewTicketResponseWithDefaults instantiates a new TicketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTicketResponseWithDefaults() *TicketResponse {
	this := TicketResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *TicketResponse) GetResult() Result {
	if o == nil {
		var ret Result
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *TicketResponse) GetResultOk() (*Result, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *TicketResponse) SetResult(v Result) {
	o.Result = v
}

// GetTicket returns the Ticket field value
func (o *TicketResponse) GetTicket() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ticket
}

// GetTicketOk returns a tuple with the Ticket field value
// and a boolean to check if the value has been set.
func (o *TicketResponse) GetTicketOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ticket, true
}

// SetTicket sets field value
func (o *TicketResponse) SetTicket(v string) {
	o.Ticket = v
}

// GetRedirectUrl returns the RedirectUrl field value
func (o *TicketResponse) GetRedirectUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
func (o *TicketResponse) GetRedirectUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *TicketResponse) SetRedirectUrl(v string) {
	o.RedirectUrl = v
}

func (o TicketResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TicketResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["ticket"] = o.Ticket
	toSerialize["redirectUrl"] = o.RedirectUrl

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TicketResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"ticket",
		"redirectUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTicketResponse := _TicketResponse{}

	err = json.Unmarshal(data, &varTicketResponse)

	if err != nil {
		return err
	}

	*o = TicketResponse(varTicketResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		delete(additionalProperties, "ticket")
		delete(additionalProperties, "redirectUrl")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTicketResponse struct {
	value *TicketResponse
	isSet bool
}

func (v NullableTicketResponse) Get() *TicketResponse {
	return v.value
}

func (v *NullableTicketResponse) Set(val *TicketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketResponse(val *TicketResponse) *NullableTicketResponse {
	return &NullableTicketResponse{value: val, isSet: true}
}

func (v NullableTicketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


