/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
)

// checks if the BasketDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasketDetails{}

// BasketDetails struct for BasketDetails
type BasketDetails struct {
	// required for CREDIT/BNPL purchases
	BasketId *string `json:"basketId,omitempty"`
	Items []BasketItem `json:"items,omitempty"`
}

// NewBasketDetails instantiates a new BasketDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasketDetails() *BasketDetails {
	this := BasketDetails{}
	return &this
}

// NewBasketDetailsWithDefaults instantiates a new BasketDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasketDetailsWithDefaults() *BasketDetails {
	this := BasketDetails{}
	return &this
}

// GetBasketId returns the BasketId field value if set, zero value otherwise.
func (o *BasketDetails) GetBasketId() string {
	if o == nil || IsNil(o.BasketId) {
		var ret string
		return ret
	}
	return *o.BasketId
}

// GetBasketIdOk returns a tuple with the BasketId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketDetails) GetBasketIdOk() (*string, bool) {
	if o == nil || IsNil(o.BasketId) {
		return nil, false
	}
	return o.BasketId, true
}

// HasBasketId returns a boolean if a field has been set.
func (o *BasketDetails) HasBasketId() bool {
	if o != nil && !IsNil(o.BasketId) {
		return true
	}

	return false
}

// SetBasketId gets a reference to the given string and assigns it to the BasketId field.
func (o *BasketDetails) SetBasketId(v string) {
	o.BasketId = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *BasketDetails) GetItems() []BasketItem {
	if o == nil || IsNil(o.Items) {
		var ret []BasketItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketDetails) GetItemsOk() ([]BasketItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *BasketDetails) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []BasketItem and assigns it to the Items field.
func (o *BasketDetails) SetItems(v []BasketItem) {
	o.Items = v
}

func (o BasketDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasketDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BasketId) {
		toSerialize["basketId"] = o.BasketId
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableBasketDetails struct {
	value *BasketDetails
	isSet bool
}

func (v NullableBasketDetails) Get() *BasketDetails {
	return v.value
}

func (v *NullableBasketDetails) Set(val *BasketDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableBasketDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableBasketDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasketDetails(val *BasketDetails) *NullableBasketDetails {
	return &NullableBasketDetails{value: val, isSet: true}
}

func (v NullableBasketDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasketDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


