/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
)

// checks if the BasketItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasketItem{}

// BasketItem struct for BasketItem
type BasketItem struct {
	SellerId *string `json:"sellerId,omitempty"`
	SupplierId *string `json:"supplierId,omitempty"`
	ProductCode *string `json:"productCode,omitempty"`
	Brand *string `json:"brand,omitempty"`
	ProductType *int32 `json:"productType,omitempty"`
	Count *int32 `json:"count,omitempty"`
	CategoryId *string `json:"categoryId,omitempty"`
}

// NewBasketItem instantiates a new BasketItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasketItem() *BasketItem {
	this := BasketItem{}
	return &this
}

// NewBasketItemWithDefaults instantiates a new BasketItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasketItemWithDefaults() *BasketItem {
	this := BasketItem{}
	return &this
}

// GetSellerId returns the SellerId field value if set, zero value otherwise.
func (o *BasketItem) GetSellerId() string {
	if o == nil || IsNil(o.SellerId) {
		var ret string
		return ret
	}
	return *o.SellerId
}

// GetSellerIdOk returns a tuple with the SellerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetSellerIdOk() (*string, bool) {
	if o == nil || IsNil(o.SellerId) {
		return nil, false
	}
	return o.SellerId, true
}

// HasSellerId returns a boolean if a field has been set.
func (o *BasketItem) HasSellerId() bool {
	if o != nil && !IsNil(o.SellerId) {
		return true
	}

	return false
}

// SetSellerId gets a reference to the given string and assigns it to the SellerId field.
func (o *BasketItem) SetSellerId(v string) {
	o.SellerId = &v
}

// GetSupplierId returns the SupplierId field value if set, zero value otherwise.
func (o *BasketItem) GetSupplierId() string {
	if o == nil || IsNil(o.SupplierId) {
		var ret string
		return ret
	}
	return *o.SupplierId
}

// GetSupplierIdOk returns a tuple with the SupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetSupplierIdOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierId) {
		return nil, false
	}
	return o.SupplierId, true
}

// HasSupplierId returns a boolean if a field has been set.
func (o *BasketItem) HasSupplierId() bool {
	if o != nil && !IsNil(o.SupplierId) {
		return true
	}

	return false
}

// SetSupplierId gets a reference to the given string and assigns it to the SupplierId field.
func (o *BasketItem) SetSupplierId(v string) {
	o.SupplierId = &v
}

// GetProductCode returns the ProductCode field value if set, zero value otherwise.
func (o *BasketItem) GetProductCode() string {
	if o == nil || IsNil(o.ProductCode) {
		var ret string
		return ret
	}
	return *o.ProductCode
}

// GetProductCodeOk returns a tuple with the ProductCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetProductCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ProductCode) {
		return nil, false
	}
	return o.ProductCode, true
}

// HasProductCode returns a boolean if a field has been set.
func (o *BasketItem) HasProductCode() bool {
	if o != nil && !IsNil(o.ProductCode) {
		return true
	}

	return false
}

// SetProductCode gets a reference to the given string and assigns it to the ProductCode field.
func (o *BasketItem) SetProductCode(v string) {
	o.ProductCode = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *BasketItem) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *BasketItem) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *BasketItem) SetBrand(v string) {
	o.Brand = &v
}

// GetProductType returns the ProductType field value if set, zero value otherwise.
func (o *BasketItem) GetProductType() int32 {
	if o == nil || IsNil(o.ProductType) {
		var ret int32
		return ret
	}
	return *o.ProductType
}

// GetProductTypeOk returns a tuple with the ProductType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetProductTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.ProductType) {
		return nil, false
	}
	return o.ProductType, true
}

// HasProductType returns a boolean if a field has been set.
func (o *BasketItem) HasProductType() bool {
	if o != nil && !IsNil(o.ProductType) {
		return true
	}

	return false
}

// SetProductType gets a reference to the given int32 and assigns it to the ProductType field.
func (o *BasketItem) SetProductType(v int32) {
	o.ProductType = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *BasketItem) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *BasketItem) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *BasketItem) SetCount(v int32) {
	o.Count = &v
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise.
func (o *BasketItem) GetCategoryId() string {
	if o == nil || IsNil(o.CategoryId) {
		var ret string
		return ret
	}
	return *o.CategoryId
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BasketItem) GetCategoryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CategoryId) {
		return nil, false
	}
	return o.CategoryId, true
}

// HasCategoryId returns a boolean if a field has been set.
func (o *BasketItem) HasCategoryId() bool {
	if o != nil && !IsNil(o.CategoryId) {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given string and assigns it to the CategoryId field.
func (o *BasketItem) SetCategoryId(v string) {
	o.CategoryId = &v
}

func (o BasketItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasketItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SellerId) {
		toSerialize["sellerId"] = o.SellerId
	}
	if !IsNil(o.SupplierId) {
		toSerialize["supplierId"] = o.SupplierId
	}
	if !IsNil(o.ProductCode) {
		toSerialize["productCode"] = o.ProductCode
	}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if !IsNil(o.ProductType) {
		toSerialize["productType"] = o.ProductType
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.CategoryId) {
		toSerialize["categoryId"] = o.CategoryId
	}
	return toSerialize, nil
}

type NullableBasketItem struct {
	value *BasketItem
	isSet bool
}

func (v NullableBasketItem) Get() *BasketItem {
	return v.value
}

func (v *NullableBasketItem) Set(val *BasketItem) {
	v.value = val
	v.isSet = true
}

func (v NullableBasketItem) IsSet() bool {
	return v.isSet
}

func (v *NullableBasketItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasketItem(val *BasketItem) *NullableBasketItem {
	return &NullableBasketItem{value: val, isSet: true}
}

func (v NullableBasketItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasketItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


