/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"fmt"
)

// checks if the VerifyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyResponse{}

// VerifyResponse struct for VerifyResponse
type VerifyResponse struct {
	Result Result `json:"result"`
	TrackingCode string `json:"trackingCode"`
	ProviderId *string `json:"providerId,omitempty"`
	Amount interface{} `json:"amount,omitempty"`
	AdditionalInfo *VerifyAdditionalInfo `json:"additionalInfo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VerifyResponse VerifyResponse

// NewVerifyResponse instantiates a new VerifyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyResponse(result Result, trackingCode string) *VerifyResponse {
	this := VerifyResponse{}
	this.Result = result
	this.TrackingCode = trackingCode
	return &this
}

// NewVerifyResponseWithDefaults instantiates a new VerifyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyResponseWithDefaults() *VerifyResponse {
	this := VerifyResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *VerifyResponse) GetResult() Result {
	if o == nil {
		var ret Result
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *VerifyResponse) GetResultOk() (*Result, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *VerifyResponse) SetResult(v Result) {
	o.Result = v
}

// GetTrackingCode returns the TrackingCode field value
func (o *VerifyResponse) GetTrackingCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingCode
}

// GetTrackingCodeOk returns a tuple with the TrackingCode field value
// and a boolean to check if the value has been set.
func (o *VerifyResponse) GetTrackingCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingCode, true
}

// SetTrackingCode sets field value
func (o *VerifyResponse) SetTrackingCode(v string) {
	o.TrackingCode = v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *VerifyResponse) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId) {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyResponse) GetProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *VerifyResponse) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *VerifyResponse) SetProviderId(v string) {
	o.ProviderId = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VerifyResponse) GetAmount() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VerifyResponse) GetAmountOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return &o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *VerifyResponse) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given interface{} and assigns it to the Amount field.
func (o *VerifyResponse) SetAmount(v interface{}) {
	o.Amount = v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *VerifyResponse) GetAdditionalInfo() VerifyAdditionalInfo {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret VerifyAdditionalInfo
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyResponse) GetAdditionalInfoOk() (*VerifyAdditionalInfo, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *VerifyResponse) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given VerifyAdditionalInfo and assigns it to the AdditionalInfo field.
func (o *VerifyResponse) SetAdditionalInfo(v VerifyAdditionalInfo) {
	o.AdditionalInfo = &v
}

func (o VerifyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["trackingCode"] = o.TrackingCode
	if !IsNil(o.ProviderId) {
		toSerialize["providerId"] = o.ProviderId
	}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VerifyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"trackingCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyResponse := _VerifyResponse{}

	err = json.Unmarshal(data, &varVerifyResponse)

	if err != nil {
		return err
	}

	*o = VerifyResponse(varVerifyResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		delete(additionalProperties, "trackingCode")
		delete(additionalProperties, "providerId")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "additionalInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVerifyResponse struct {
	value *VerifyResponse
	isSet bool
}

func (v NullableVerifyResponse) Get() *VerifyResponse {
	return v.value
}

func (v *NullableVerifyResponse) Set(val *VerifyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyResponse(val *VerifyResponse) *NullableVerifyResponse {
	return &NullableVerifyResponse{value: val, isSet: true}
}

func (v NullableVerifyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


