/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefundRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefundRequest{}

// RefundRequest struct for RefundRequest
type RefundRequest struct {
	// unique merchant-generated id for this refund, which must differ from the providerId of the purchase being returned
	ProviderId string `json:"providerId"`
	// amount to return to the customer in Rials, up to the original purchase amount
	Amount int64 `json:"amount"`
	// trackingCode of the original purchase being returned
	SaleTrackingCode string `json:"saleTrackingCode"`
}

type _RefundRequest RefundRequest

// NewRefundRequest instantiates a new RefundRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundRequest(providerId string, amount int64, saleTrackingCode string) *RefundRequest {
	this := RefundRequest{}
	this.ProviderId = providerId
	this.Amount = amount
	this.SaleTrackingCode = saleTrackingCode
	return &this
}

// NewRefundRequestWithDefaults instantiates a new RefundRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundRequestWithDefaults() *RefundRequest {
	this := RefundRequest{}
	return &this
}

// GetProviderId returns the ProviderId field value
func (o *RefundRequest) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *RefundRequest) SetProviderId(v string) {
	o.ProviderId = v
}

// GetAmount returns the Amount field value
func (o *RefundRequest) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *RefundRequest) SetAmount(v int64) {
	o.Amount = v
}

// GetSaleTrackingCode returns the SaleTrackingCode field value
func (o *RefundRequest) GetSaleTrackingCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaleTrackingCode
}

// GetSaleTrackingCodeOk returns a tuple with the SaleTrackingCode field value
// and a boolean to check if the value has been set.
func (o *RefundRequest) GetSaleTrackingCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SaleTrackingCode, true
}

// SetSaleTrackingCode sets field value
func (o *RefundRequest) SetSaleTrackingCode(v string) {
	o.SaleTrackingCode = v
}

func (o RefundRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefundRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["providerId"] = o.ProviderId
	toSerialize["amount"] = o.Amount
	toSerialize["saleTrackingCode"] = o.SaleTrackingCode
	return toSerialize, nil
}

func (o *RefundRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"providerId",
		"amount",
		"saleTrackingCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefundRequest := _RefundRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefundRequest)

	if err != nil {
		return err
	}

	*o = RefundRequest(varRefundRequest)

	return err
}

type NullableRefundRequest struct {
	value *RefundRequest
	isSet bool
}

func (v NullableRefundRequest) Get() *RefundRequest {
	return v.value
}

func (v *NullableRefundRequest) Set(val *RefundRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundRequest(val *RefundRequest) *NullableRefundRequest {
	return &NullableRefundRequest{value: val, isSet: true}
}

func (v NullableRefundRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


