/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
)

// checks if the VerifyAdditionalInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyAdditionalInfo{}

// VerifyAdditionalInfo struct for VerifyAdditionalInfo
type VerifyAdditionalInfo struct {
	PrepaymentAmount *int64 `json:"prepaymentAmount,omitempty"`
	CashAmount *int64 `json:"cashAmount,omitempty"`
	CreditAmount *int64 `json:"creditAmount,omitempty"`
	InstantFinalization *bool `json:"instantFinalization,omitempty"`
	GenerateInvoice *bool `json:"generateInvoice,omitempty"`
}

// NewVerifyAdditionalInfo instantiates a new VerifyAdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyAdditionalInfo() *VerifyAdditionalInfo {
	this := VerifyAdditionalInfo{}
	return &this
}

// NewVerifyAdditionalInfoWithDefaults instantiates a new VerifyAdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyAdditionalInfoWithDefaults() *VerifyAdditionalInfo {
	this := VerifyAdditionalInfo{}
	return &this
}

// GetPrepaymentAmount returns the PrepaymentAmount field value if set, zero value otherwise.
func (o *VerifyAdditionalInfo) GetPrepaymentAmount() int64 {
	if o == nil || IsNil(o.PrepaymentAmount) {
		var ret int64
		return ret
	}
	return *o.PrepaymentAmount
}

// GetPrepaymentAmountOk returns a tuple with the PrepaymentAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyAdditionalInfo) GetPrepaymentAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.PrepaymentAmount) {
		return nil, false
	}
	return o.PrepaymentAmount, true
}

// HasPrepaymentAmount returns a boolean if a field has been set.
func (o *VerifyAdditionalInfo) HasPrepaymentAmount() bool {
	if o != nil && !IsNil(o.PrepaymentAmount) {
		return true
	}

	return false
}

// SetPrepaymentAmount gets a reference to the given int64 and assigns it to the PrepaymentAmount field.
func (o *VerifyAdditionalInfo) SetPrepaymentAmount(v int64) {
	o.PrepaymentAmount = &v
}

// GetCashAmount returns the CashAmount field value if set, zero value otherwise.
func (o *VerifyAdditionalInfo) GetCashAmount() int64 {
	if o == nil || IsNil(o.CashAmount) {
		var ret int64
		return ret
	}
	return *o.CashAmount
}

// GetCashAmountOk returns a tuple with the CashAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyAdditionalInfo) GetCashAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.CashAmount) {
		return nil, false
	}
	return o.CashAmount, true
}

// HasCashAmount returns a boolean if a field has been set.
func (o *VerifyAdditionalInfo) HasCashAmount() bool {
	if o != nil && !IsNil(o.CashAmount) {
		return true
	}

	return false
}

// SetCashAmount gets a reference to the given int64 and assigns it to the CashAmount field.
func (o *VerifyAdditionalInfo) SetCashAmount(v int64) {
	o.CashAmount = &v
}

// GetCreditAmount returns the CreditAmount field value if set, zero value otherwise.
func (o *VerifyAdditionalInfo) GetCreditAmount() int64 {
	if o == nil || IsNil(o.CreditAmount) {
		var ret int64
		return ret
	}
	return *o.CreditAmount
}

// GetCreditAmountOk returns a tuple with the CreditAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyAdditionalInfo) GetCreditAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.CreditAmount) {
		return nil, false
	}
	return o.CreditAmount, true
}

// HasCreditAmount returns a boolean if a field has been set.
func (o *VerifyAdditionalInfo) HasCreditAmount() bool {
	if o != nil && !IsNil(o.CreditAmount) {
		return true
	}

	return false
}

// SetCreditAmount gets a reference to the given int64 and assigns it to the CreditAmount field.
func (o *VerifyAdditionalInfo) SetCreditAmount(v int64) {
	o.CreditAmount = &v
}

// GetInstantFinalization returns the InstantFinalization field value if set, zero value otherwise.
func (o *VerifyAdditionalInfo) GetInstantFinalization() bool {
	if o == nil || IsNil(o.InstantFinalization) {
		var ret bool
		return ret
	}
	return *o.InstantFinalization
}

// GetInstantFinalizationOk returns a tuple with the InstantFinalization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyAdditionalInfo) GetInstantFinalizationOk() (*bool, bool) {
	if o == nil || IsNil(o.InstantFinalization) {
		return nil, false
	}
	return o.InstantFinalization, true
}

// HasInstantFinalization returns a boolean if a field has been set.
func (o *VerifyAdditionalInfo) HasInstantFinalization() bool {
	if o != nil && !IsNil(o.InstantFinalization) {
		return true
	}

	return false
}

// SetInstantFinalization gets a reference to the given bool and assigns it to the InstantFinalization field.
func (o *VerifyAdditionalInfo) SetInstantFinalization(v bool) {
	o.InstantFinalization = &v
}

// GetGenerateInvoice returns the GenerateInvoice field value if set, zero value otherwise.
func (o *VerifyAdditionalInfo) GetGenerateInvoice() bool {
	if o == nil || IsNil(o.GenerateInvoice) {
		var ret bool
		return ret
	}
	return *o.GenerateInvoice
}

// GetGenerateInvoiceOk returns a tuple with the GenerateInvoice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerifyAdditionalInfo) GetGenerateInvoiceOk() (*bool, bool) {
	if o == nil || IsNil(o.GenerateInvoice) {
		return nil, false
	}
	return o.GenerateInvoice, true
}

// HasGenerateInvoice returns a boolean if a field has been set.
func (o *VerifyAdditionalInfo) HasGenerateInvoice() bool {
	if o != nil && !IsNil(o.GenerateInvoice) {
		return true
	}

	return false
}

// SetGenerateInvoice gets a reference to the given bool and assigns it to the GenerateInvoice field.
func (o *VerifyAdditionalInfo) SetGenerateInvoice(v bool) {
	o.GenerateInvoice = &v
}

func (o VerifyAdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyAdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrepaymentAmount) {
		toSerialize["prepaymentAmount"] = o.PrepaymentAmount
	}
	if !IsNil(o.CashAmount) {
		toSerialize["cashAmount"] = o.CashAmount
	}
	if !IsNil(o.CreditAmount) {
		toSerialize["creditAmount"] = o.CreditAmount
	}
	if !IsNil(o.InstantFinalization) {
		toSerialize["instantFinalization"] = o.InstantFinalization
	}
	if !IsNil(o.GenerateInvoice) {
		toSerialize["generateInvoice"] = o.GenerateInvoice
	}
	return toSerialize, nil
}

type NullableVerifyAdditionalInfo struct {
	value *VerifyAdditionalInfo
	isSet bool
}

func (v NullableVerifyAdditionalInfo) Get() *VerifyAdditionalInfo {
	return v.value
}

func (v *NullableVerifyAdditionalInfo) Set(val *VerifyAdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyAdditionalInfo(val *VerifyAdditionalInfo) *NullableVerifyAdditionalInfo {
	return &NullableVerifyAdditionalInfo{value: val, isSet: true}
}

func (v NullableVerifyAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


