/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"fmt"
)

// checks if the DeliverResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliverResponse{}

// DeliverResponse struct for DeliverResponse
type DeliverResponse struct {
	Result Result `json:"result"`
	AdditionalProperties map[string]interface{}
}

type _DeliverResponse DeliverResponse

// NewDeliverResponse instantiates a new DeliverResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliverResponse(result Result) *DeliverResponse {
	this := DeliverResponse{}
	this.Result = result
	return &this
}

// NewDeliverResponseWithDefaults instantiates a new DeliverResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliverResponseWithDefaults() *DeliverResponse {
	this := DeliverResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *DeliverResponse) GetResult() Result {
	if o == nil {
		var ret Result
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *DeliverResponse) GetResultOk() (*Result, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *DeliverResponse) SetResult(v Result) {
	o.Result = v
}

func (o DeliverResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliverResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeliverResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliverResponse := _DeliverResponse{}

	err = json.Unmarshal(data, &varDeliverResponse)

	if err != nil {
		return err
	}

	*o = DeliverResponse(varDeliverResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeliverResponse struct {
	value *DeliverResponse
	isSet bool
}

func (v NullableDeliverResponse) Get() *DeliverResponse {
	return v.value
}

func (v *NullableDeliverResponse) Set(val *DeliverResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliverResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliverResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliverResponse(val *DeliverResponse) *NullableDeliverResponse {
	return &NullableDeliverResponse{value: val, isSet: true}
}

func (v NullableDeliverResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliverResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


