/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyRequest{}

// VerifyRequest struct for VerifyRequest
type VerifyRequest struct {
	// purchase tracking code
	TrackingCode string `json:"trackingCode"`
	// same providerId sent during ticket creation
	ProviderId string `json:"providerId"`
}

type _VerifyRequest VerifyRequest

// NewVerifyRequest instantiates a new VerifyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyRequest(trackingCode string, providerId string) *VerifyRequest {
	this := VerifyRequest{}
	this.TrackingCode = trackingCode
	this.ProviderId = providerId
	return &this
}

// NewVerifyRequestWithDefaults instantiates a new VerifyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyRequestWithDefaults() *VerifyRequest {
	this := VerifyRequest{}
	return &this
}

// GetTrackingCode returns the TrackingCode field value
func (o *VerifyRequest) GetTrackingCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingCode
}

// GetTrackingCodeOk returns a tuple with the TrackingCode field value
// and a boolean to check if the value has been set.
func (o *VerifyRequest) GetTrackingCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingCode, true
}

// SetTrackingCode sets field value
func (o *VerifyRequest) SetTrackingCode(v string) {
	o.TrackingCode = v
}

// GetProviderId returns the ProviderId field value
func (o *VerifyRequest) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *VerifyRequest) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *VerifyRequest) SetProviderId(v string) {
	o.ProviderId = v
}

func (o VerifyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["trackingCode"] = o.TrackingCode
	toSerialize["providerId"] = o.ProviderId
	return toSerialize, nil
}

func (o *VerifyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"trackingCode",
		"providerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyRequest := _VerifyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyRequest)

	if err != nil {
		return err
	}

	*o = VerifyRequest(varVerifyRequest)

	return err
}

type NullableVerifyRequest struct {
	value *VerifyRequest
	isSet bool
}

func (v NullableVerifyRequest) Get() *VerifyRequest {
	return v.value
}

func (v *NullableVerifyRequest) Set(val *VerifyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyRequest(val *VerifyRequest) *NullableVerifyRequest {
	return &NullableVerifyRequest{value: val, isSet: true}
}

func (v NullableVerifyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


