/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeliverRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeliverRequest{}

// DeliverRequest struct for DeliverRequest
type DeliverRequest struct {
	// delivery time, epoch milliseconds
	DeliveryDate int64 `json:"deliveryDate"`
	InvoiceNumber string `json:"invoiceNumber"`
	TrackingCode string `json:"trackingCode"`
	Products []string `json:"products"`
}

type _DeliverRequest DeliverRequest

// NewDeliverRequest instantiates a new DeliverRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliverRequest(deliveryDate int64, invoiceNumber string, trackingCode string, products []string) *DeliverRequest {
	this := DeliverRequest{}
	this.DeliveryDate = deliveryDate
	this.InvoiceNumber = invoiceNumber
	this.TrackingCode = trackingCode
	this.Products = products
	return &this
}

// NewDeliverRequestWithDefaults instantiates a new DeliverRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliverRequestWithDefaults() *DeliverRequest {
	this := DeliverRequest{}
	return &this
}

// GetDeliveryDate returns the DeliveryDate field value
func (o *DeliverRequest) GetDeliveryDate() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DeliveryDate
}

// GetDeliveryDateOk returns a tuple with the DeliveryDate field value
// and a boolean to check if the value has been set.
func (o *DeliverRequest) GetDeliveryDateOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveryDate, true
}

// SetDeliveryDate sets field value
func (o *DeliverRequest) SetDeliveryDate(v int64) {
	o.DeliveryDate = v
}

// GetInvoiceNumber returns the InvoiceNumber field value
func (o *DeliverRequest) GetInvoiceNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceNumber
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value
// and a boolean to check if the value has been set.
func (o *DeliverRequest) GetInvoiceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceNumber, true
}

// SetInvoiceNumber sets field value
func (o *DeliverRequest) SetInvoiceNumber(v string) {
	o.InvoiceNumber = v
}

// GetTrackingCode returns the TrackingCode field value
func (o *DeliverRequest) GetTrackingCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TrackingCode
}

// GetTrackingCodeOk returns a tuple with the TrackingCode field value
// and a boolean to check if the value has been set.
func (o *DeliverRequest) GetTrackingCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingCode, true
}

// SetTrackingCode sets field value
func (o *DeliverRequest) SetTrackingCode(v string) {
	o.TrackingCode = v
}

// GetProducts returns the Products field value
func (o *DeliverRequest) GetProducts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Products
}

// GetProductsOk returns a tuple with the Products field value
// and a boolean to check if the value has been set.
func (o *DeliverRequest) GetProductsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Products, true
}

// SetProducts sets field value
func (o *DeliverRequest) SetProducts(v []string) {
	o.Products = v
}

func (o DeliverRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeliverRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deliveryDate"] = o.DeliveryDate
	toSerialize["invoiceNumber"] = o.InvoiceNumber
	toSerialize["trackingCode"] = o.TrackingCode
	toSerialize["products"] = o.Products
	return toSerialize, nil
}

func (o *DeliverRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deliveryDate",
		"invoiceNumber",
		"trackingCode",
		"products",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeliverRequest := _DeliverRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeliverRequest)

	if err != nil {
		return err
	}

	*o = DeliverRequest(varDeliverRequest)

	return err
}

type NullableDeliverRequest struct {
	value *DeliverRequest
	isSet bool
}

func (v NullableDeliverRequest) Get() *DeliverRequest {
	return v.value
}

func (v *NullableDeliverRequest) Set(val *DeliverRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliverRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliverRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliverRequest(val *DeliverRequest) *NullableDeliverRequest {
	return &NullableDeliverRequest{value: val, isSet: true}
}

func (v NullableDeliverRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliverRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


