/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TicketRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TicketRequest{}

// TicketRequest struct for TicketRequest
type TicketRequest struct {
	// customer mobile number
	CellNumber string `json:"cellNumber"`
	// purchase amount in Rials
	Amount int64 `json:"amount"`
	// unique merchant-generated id for this purchase
	ProviderId string `json:"providerId"`
	CallbackUrl string `json:"callbackUrl"`
	BasketDetailsDto *BasketDetails `json:"basketDetailsDto,omitempty"`
	AdditionalInfo *AdditionalInfo `json:"additionalInfo,omitempty"`
}

type _TicketRequest TicketRequest

// NewTicketRequest instantiates a new TicketRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTicketRequest(cellNumber string, amount int64, providerId string, callbackUrl string) *TicketRequest {
	this := TicketRequest{}
	this.CellNumber = cellNumber
	this.Amount = amount
	this.ProviderId = providerId
	this.CallbackUrl = callbackUrl
	return &this
}

// NewTicketRequestWithDefaults instantiates a new TicketRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTicketRequestWithDefaults() *TicketRequest {
	this := TicketRequest{}
	return &this
}

// GetCellNumber returns the CellNumber field value
func (o *TicketRequest) GetCellNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CellNumber
}

// GetCellNumberOk returns a tuple with the CellNumber field value
// and a boolean to check if the value has been set.
func (o *TicketRequest) GetCellNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CellNumber, true
}

// SetCellNumber sets field value
func (o *TicketRequest) SetCellNumber(v string) {
	o.CellNumber = v
}

// GetAmount returns the Amount field value
func (o *TicketRequest) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TicketRequest) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TicketRequest) SetAmount(v int64) {
	o.Amount = v
}

// GetProviderId returns the ProviderId field value
func (o *TicketRequest) GetProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *TicketRequest) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *TicketRequest) SetProviderId(v string) {
	o.ProviderId = v
}

// GetCallbackUrl returns the CallbackUrl field value
func (o *TicketRequest) GetCallbackUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value
// and a boolean to check if the value has been set.
func (o *TicketRequest) GetCallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallbackUrl, true
}

// SetCallbackUrl sets field value
func (o *TicketRequest) SetCallbackUrl(v string) {
	o.CallbackUrl = v
}

// GetBasketDetailsDto returns the BasketDetailsDto field value if set, zero value otherwise.
func (o *TicketRequest) GetBasketDetailsDto() BasketDetails {
	if o == nil || IsNil(o.BasketDetailsDto) {
		var ret BasketDetails
		return ret
	}
	return *o.BasketDetailsDto
}

// GetBasketDetailsDtoOk returns a tuple with the BasketDetailsDto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TicketRequest) GetBasketDetailsDtoOk() (*BasketDetails, bool) {
	if o == nil || IsNil(o.BasketDetailsDto) {
		return nil, false
	}
	return o.BasketDetailsDto, true
}

// HasBasketDetailsDto returns a boolean if a field has been set.
func (o *TicketRequest) HasBasketDetailsDto() bool {
	if o != nil && !IsNil(o.BasketDetailsDto) {
		return true
	}

	return false
}

// SetBasketDetailsDto gets a reference to the given BasketDetails and assigns it to the BasketDetailsDto field.
func (o *TicketRequest) SetBasketDetailsDto(v BasketDetails) {
	o.BasketDetailsDto = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *TicketRequest) GetAdditionalInfo() AdditionalInfo {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret AdditionalInfo
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TicketRequest) GetAdditionalInfoOk() (*AdditionalInfo, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *TicketRequest) HasAdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given AdditionalInfo and assigns it to the AdditionalInfo field.
func (o *TicketRequest) SetAdditionalInfo(v AdditionalInfo) {
	o.AdditionalInfo = &v
}

func (o TicketRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TicketRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cellNumber"] = o.CellNumber
	toSerialize["amount"] = o.Amount
	toSerialize["providerId"] = o.ProviderId
	toSerialize["callbackUrl"] = o.CallbackUrl
	if !IsNil(o.BasketDetailsDto) {
		toSerialize["basketDetailsDto"] = o.BasketDetailsDto
	}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	return toSerialize, nil
}

func (o *TicketRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cellNumber",
		"amount",
		"providerId",
		"callbackUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTicketRequest := _TicketRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTicketRequest)

	if err != nil {
		return err
	}

	*o = TicketRequest(varTicketRequest)

	return err
}

type NullableTicketRequest struct {
	value *TicketRequest
	isSet bool
}

func (v NullableTicketRequest) Get() *TicketRequest {
	return v.value
}

func (v *NullableTicketRequest) Set(val *TicketRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTicketRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTicketRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTicketRequest(val *TicketRequest) *NullableTicketRequest {
	return &NullableTicketRequest{value: val, isSet: true}
}

func (v NullableTicketRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTicketRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


