/*
DigiPay UPG API

DigiPay Unified Payment Gateway (UPG) API - Wallet and BNPL (Buy Now Pay Later) purchase flow

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digipay

import (
	"encoding/json"
)

// checks if the AdditionalInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalInfo{}

// AdditionalInfo struct for AdditionalInfo
type AdditionalInfo struct {
	// skips the payment method selection screen when set
	PreferredGateway *int32 `json:"preferredGateway,omitempty"`
}

// NewAdditionalInfo instantiates a new AdditionalInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalInfo() *AdditionalInfo {
	this := AdditionalInfo{}
	return &this
}

// NewAdditionalInfoWithDefaults instantiates a new AdditionalInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalInfoWithDefaults() *AdditionalInfo {
	this := AdditionalInfo{}
	return &this
}

// GetPreferredGateway returns the PreferredGateway field value if set, zero value otherwise.
func (o *AdditionalInfo) GetPreferredGateway() int32 {
	if o == nil || IsNil(o.PreferredGateway) {
		var ret int32
		return ret
	}
	return *o.PreferredGateway
}

// GetPreferredGatewayOk returns a tuple with the PreferredGateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalInfo) GetPreferredGatewayOk() (*int32, bool) {
	if o == nil || IsNil(o.PreferredGateway) {
		return nil, false
	}
	return o.PreferredGateway, true
}

// HasPreferredGateway returns a boolean if a field has been set.
func (o *AdditionalInfo) HasPreferredGateway() bool {
	if o != nil && !IsNil(o.PreferredGateway) {
		return true
	}

	return false
}

// SetPreferredGateway gets a reference to the given int32 and assigns it to the PreferredGateway field.
func (o *AdditionalInfo) SetPreferredGateway(v int32) {
	o.PreferredGateway = &v
}

func (o AdditionalInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PreferredGateway) {
		toSerialize["preferredGateway"] = o.PreferredGateway
	}
	return toSerialize, nil
}

type NullableAdditionalInfo struct {
	value *AdditionalInfo
	isSet bool
}

func (v NullableAdditionalInfo) Get() *AdditionalInfo {
	return v.value
}

func (v *NullableAdditionalInfo) Set(val *AdditionalInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalInfo(val *AdditionalInfo) *NullableAdditionalInfo {
	return &NullableAdditionalInfo{value: val, isSet: true}
}

func (v NullableAdditionalInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


